### ISSUE TITLE
seems like a issue with the conversion/map

### ISSUE THREAD

**Issue by CVineeth** [peteroupc/CBOR#24]
Hi Peter
Consider the following code snippets 
1.
            var cborObj = CBORObject.NewMap()                .Add(1, 3)                .Add(2, 4);             string jsonStr = cborObj.ToJSONString(); 
2.
            cborObj = CBORObject.NewMap()
               .Add("1", 3)
               .Add("2", 4);
               jsonStr = cborObj.ToJSONString();

The both will give a JSON string 
{
	"1": 4,
	"2": 2
}
But in the first one I have put int value as key. In second string value.
Also when we consider JSON the key needs to be in string format.

The advantage of fist option is less bytes when we convert in to bytes (EncodeToBytes()) But the problem I we can't create a C# class property name as an integer hence can't do the object conversion.

So seems like a issue with the conversion/map. Could you please correct the same or let me know I am wrong.

Vineeth

**Comment by peteroupc** [comment]
In both cases, the JSON keys will be strings because JSON key values can only be strings, not numbers or any other values.  Also, you are correct in that C# property names can't start with a number.  What are you ultimately trying to do?  Are you trying to deserialize the JSON via CBORObject to a C# object (using the ToObject method)?  In that case, it won't currently work well if the map's keys start with a number, and you will have to use an alternative approach (such as using arrays instead of maps if you're using numbers as keys).

**Comment by CVineeth** [comment]
I have to send data to another system with less size. If i am using the above first option the data size will be less but direct decoding to an C# object (for future usage ) is not possible. and the data will be a mix of map and array.

**Comment by peteroupc** [comment]
Can you show some code where you show that my CBOR library fails to decode to a C# object?  Does it work with the first example (integer map keys)?  The second example (string map keys)?  What "C# object" do you mean?

**Comment by CVineeth** [comment]
Just considering the following code snippets. I am just trying to create a COBRObject and convert in to JSON and then create another CBORObject using the converted JSON of first Object. Ideally the CBORObject should be same.

`//creating a new CBORObject
var Obj1 = CBORObject.NewMap()
.Add(1, 5);
//converting the CBOR Object to string
string Obj1String = Obj1.ToString();
Console.WriteLine(string.Concat("Obj1 - CBOR String: ", Obj1String));
//converting to JSON
string Obj1Json = Obj1.ToJSONString();
Console.WriteLine(string.Concat("Obj1 - JSON: ", Obj1Json));


//Creatring a new CBORObject using the above JSON - Obj1Json
CBORObject Obj2 = CBORObject.FromJSONString(Obj1Json);
//converting the CBOR Object to string
string Obj2String = Obj2.ToString();
Console.WriteLine(string.Concat("Obj2 - CBOR String: ", Obj2String));
//converting to JSON
string Obj2JSON = Obj2.ToJSONString();
Console.WriteLine(string.Concat("Obj2 - JSON: ", Obj2JSON));

//Ideally the above CBORObject's should be same ? 
// Because I am using first CBORObject converted JSON to create second CBORObject
int result = Obj1.CompareTo(Obj2);

if (result == 0)
{
    Console.WriteLine("Same");
}
else
{
    Console.WriteLine("Not Same");
}`

I am not saying your CBOR library fails but I want to know whether this is the right behaviour or not. So that we can use CBOR in our project accordingly
As per my understanding RFC 7049 - 1.1.  Objectives 6,7 are fails in my code. I am not able to encode/decode the CBORObject correctly. Please correct me if I am doing wrong.

**Comment by peteroupc** [comment]
I am afraid this behavior is by design.

In general, if you convert a CBOR object with integer map keys to JSON and back to a CBOR object, you _can't_ expect the new CBOR object to be exactly the same as the original.  Read objective 6 again:

> [The CBOR format] must support a reasonable level of conversion [to and from JSON] **as long as the data represented is within the capabilities of JSON**.

In that sense, integer map keys are not "within the capabilities of JSON", since JSON supports only strings as map keys.  Moreover, converting integer map keys to strings is just one of many things the library does in the conversion from CBOR to JSON.  In that sense, the CBOR-to-JSON conversion is lossy.  This is the same in other JSON libraries.  For example, run the following in a Ruby interpreter:

    require 'json'
    x="{\"1\":2,\"3\":4}"
    puts JSON.parse(x)
    puts JSON.generate({1=>2})

You will see, here too, that the keys in the converted JSON object are strings, not numbers.

**Comment by CVineeth** [comment]
OK. Thanks for your time and information.
