### ISSUE TITLE
Get-only props are not included

### ISSUE THREAD

**Issue by slipdef** [peteroupc/CBOR#30]
Have a class with a prop that doesn't have setter. CBOR.FromObject() omits such props.

**Comment by peteroupc** [comment]
This is by design.  The .NET library, by default, supports only read-write properties (with the exception of compiler-generated properties, where read-only properties are also supported).  Supporting read-only properties could expose the library to security risks, since properties could be implemented to do something other than query the value of a field.  The Java version of this library is limited in the same way for the same reason (and without an exception for compiler-generated types).

To convert objects of a custom type to and from CBOR, pass a CBORTypeMapper along with the object (see the documentation for [CBORTypeMapper](https://peteroupc.github.io/CBOR/docs/PeterO.Cbor.CBORTypeMapper.html) for more information).

**Comment by slipdef** [comment]
Not sure I follow why read-write properties are guaranteed not to expose the lib to the risk you mentioned.
Anyways, if it's by design I need to deal with it on my side.

**Comment by peteroupc** [comment]
I don't mean to imply that read-write properties are _guaranteed_ to have no security risks.   It's just that they are more likely to come from a plain-old-data class (also known as POCO class in .NET).  In addition, even read-write properties of certain types are not supported by `FromObject`.  Finally, the documentation has a security note for `FromObject` (and a similar one for `ToObject`) as follows:  "For security reasons, whenever possible, an application should not base this parameter on user input or other externally supplied data unless the application limits this parameter's inputs to types specially handled by this method (such as `int` or `String`) and/or to plain-old-data types (POCO or POJO types) within the control of the application."
