### ISSUE TITLE
Async version?

### ISSUE THREAD

**Issue by VasilyFomin** [peteroupc/CBOR#32]
Hi,

Thanks for the library. I'm wondering if you have any plans to work on the async support?

**Comment by peteroupc** [comment]
Async support might not be there for a while.  There are several things that come into play here:

- There is a risk of code duplication.
    - The async/await version of the relevant methods will be very similar to the non-async version.
    - Having a non-async version with substantially the same code is needed for compatibility with the .NET 2.0 and 4.0 versions and consistency with the Java version.  For example, compare the [async/await versions](https://github.com/peteroupc/CBOR/blob/master/CBOR/PeterO/Cbor/CBORReader.cs) with the non-async version.
- Also, apparently, code analysis suggests to include ConfigureAwait on any await which sounds burdensome, unnatural, or both.

**Comment by VasilyFomin** [comment]
As someone who recently added async support to a sync library, I can only agree that it's a pain.

In the end, I used "The Flag Argument Hack" from [Async Programming - Brownfield Async Development by Stephen Cleary](https://msdn.microsoft.com/magazine/mt238404) to reuse the code without the risk of a deadlock, and yes, you need to `ConfigureAwait(false)` in each `await`ed call.

Looking at the sample you provided you had an initial version already, did you stop for the reasons above?

**Comment by peteroupc** [comment]
I have decided against supporting async functions for now.

Especially when writing small CBOR objects (no more than 1024 bytes as required, for example, by the Client-to-Authenticator Protocol by default), it's generally enough to use `EncodeToBytes` and write the resulting byte array using existing async methods (e.g., `Stream.WriteAsync()`).  In the case of reading CBOR objects, a higher-level protocol usually provides the byte length, which is usually small, so that existing async methods (e.g., `Stream.ReadAsync()`) can be used to read those bytes and `DecodeToBytes` then used.  Note that `EncodeToBytes` and `DecodeToBytes` are CPU-bound, so they won't benefit from `async`.
