### ISSUE TITLE
From Bytes to Object to JSON and back

### ISSUE THREAD

**Issue by CIMOha** [peteroupc/CBOR#35]
Hello Sir

I am having trouble to use your tools decoding from bytes to Object to JSON.

            byte[] bytes = ToBytes("a201187b021901c8");     //

            CBORObject obj1 = CBORObject.DecodeFromBytes(bytes);
            string w = obj1.ToJSONString();
            CBORObject obj2 = CBORObject.FromJSONString(w);

            byte[] f = obj1.EncodeToBytes();
            byte[] r = obj2.EncodeToBytes();

I would expect the two byte arrays f and r to be completely identical but they are not.
Do You have a comment on that?

Ole

**Comment by peteroupc** [comment]
It appears your CBOR data is of a map with integer map keys.  However, JSON doesn't support integer map keys, so such keys are converted to strings.  Moreover, as I mentioned in #24:

> In general, if you convert a CBOR object with integer map keys to JSON and back to a CBOR object, you _can't_ expect the new CBOR object to be exactly the same as the original.

See #24 for more information.  This behavior is by design.

By the way, why are you converting CBOR data to JSON and back to CBOR?  Do you need the JSON data for some purposes?

**Comment by peteroupc** [comment]
No response, so closing.
