### ISSUE TITLE
Expected double header, but found F9

### ISSUE THREAD

**Issue by slipdef** [peteroupc/CBOR#47]
**Describe the bug**

Can't deserialize CBOR bytes using https://github.com/Kotlin/kotlinx.serialization if serialized object has a field with double value without fractional part.

**To Reproduce**

C#
```
  public class Data2
  {
      public double Field { get; set; }
  }

```
Kotlin

```
@Serializable
data class Data2(val field: Double)
```

Works: 
```
var works = CBORObject.FromObject(new Data2 { Field = 66.77 }).EncodeToBytes()
var res1 = Cbor.Default.decodeFromByteArray<Data2>(works)

Exception 'Expected double header, but found F9':
var doesntWork = CBORObject.FromObject(new Data2 { Field = 66 }).EncodeToBytes()
var res2 = Cbor.Default.decodeFromByteArray<Data2>(doesntWork)
```

However it worked fine with 4.0 beta1. Tested on all versions after 4.0 beta1 - crashes with that exception.

**Environment**
 - Kotlin version: 1.4
 - Library version on Kotlin side: org.jetbrains.kotlinx:kotlinx-serialization-cbor:1.0.0-RC
 - Library version on C# side: 4.2

**Comment by peteroupc** [comment]
The CBOR library encodes certain `double` values in a shorter format, namely the half-float format supported by CBOR, if that can be done without loss.  This seems to be the case here.  However, my CBOR library works correctly here; the issue is with your Kotlin serialization library, which appears not to support decoding the half-float format.  You should file an issue for that library.
